refactor: Convert server.rs to use async await
paritytech/sccache pull request #5
Opened 2020-11-12 12:33 UTC by drahnr

2020-11-12 12:57 UTC, TriplEight approved these changes
Also can be merged as it was tested in https://github.com/mozilla/sccache/pull/787

2020-11-20 15:34 UTC, gww-parity requested changes

2020-11-20 15:34 UTC, gww-parity commented on src/server.rs
> +                time::timeout(Duration::new(30, 0), wait)
does it indicate waiting 30 seconds?

If yes please update info log at line 579

2020-11-20 15:34 UTC, gww-parity commented on src/server.rs
>              "moving into the shutdown phase now, waiting at most 10 seconds \
herer to update to 30 seconds , following code review comment below

2020-11-20 15:48 UTC, drahnr commented on src/server.rs
>              "moving into the shutdown phase now, waiting at most 10 seconds \
```suggestion
            "moving into the shutdown phase now, waiting at most 30 seconds \
```

2020-11-20 15:48 UTC, gww-parity commented on src/server.rs
>              "moving into the shutdown phase now, waiting at most 10 seconds \
30 seconds (according to line 592)

2020-11-20 15:52 UTC, gww-parity approved these changes

2020-11-20 16:21 UTC, gww-parity approved these changes

2020-11-20 16:31 UTC, merged