remove openssl
paritytech/sccache pull request #7
Opened 2020-11-13 13:58 UTC by drahnr

2020-11-13 14:03 UTC, drahnr commented
Pending some unit tests to verify the results are equiv.

2020-11-13 17:43 UTC, TriplEight commented
if you're waiting travis to be rewritten to gitlab, it kinda [depends](https://github.com/paritytech/sccache/blob/36ccc87af1cc90aba0274d40d67d23aebca19829/.travis.yml#L24) on this PR.

2020-11-13 18:07 UTC, drahnr commented
This one depends on me writing some verification tests

2020-11-16 15:32 UTC, gww-parity requested changes
Regression in compiler warnings introduced with:
https://github.com/paritytech/sccache/pull/7/commits/3f030f3b8ccda40b3af248b20cfcc4bb09ebadd7

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use picky::pem::{parse_pem, Pem};
```
warning: unused imports: `Pem`, `parse_pem`
   --> src/dist/http.rs:308:22
    |
308 |     use picky::pem::{parse_pem, Pem};
    |                      ^^^^^^^^^  ^^^
    |
    = note: `#[warn(unused_imports)]` on by default
```

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use picky::x509::{certificate::CertType, csr::Csr};
```
warning: unused imports: `certificate::CertType`, `csr::Csr`
   --> src/dist/http.rs:311:23
    |
311 |     use picky::x509::{certificate::CertType, csr::Csr};
    |                       ^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^
```

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use picky::x509::key_id_gen_method::{KeyIdGenError, KeyIdGenMethod};
```
warning: unused import: `KeyIdGenError`
   --> src/dist/http.rs:310:42
    |
310 |     use picky::x509::key_id_gen_method::{KeyIdGenError, KeyIdGenMethod};
    |                                          ^^^^^^^^^^^^^

```

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use picky::x509::Extension;
```
warning: unused import: `picky::x509::Extension`
   --> src/dist/http.rs:317:9
    |
317 |     use picky::x509::Extension;
    |         ^^^^^^^^^^^^^^^^^^^^^^
```

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use sha2::{Sha256, Sha512, Digest};
```
warning: unused imports: `Sha256`, `Sha512`
   --> src/dist/http.rs:319:16
    |
319 |     use sha2::{Sha256, Sha512, Digest};
    |                ^^^^^^  ^^^^^^

```

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use std::convert::TryFrom;
```
warning: unused import: `std::convert::TryFrom`
   --> src/dist/http.rs:324:9
    |
324 |     use std::convert::TryFrom;
    |         ^^^^^^^^^^^^^^^^^^^^^

```

2020-11-16 15:32 UTC, gww-parity commented on src/dist/http.rs
> +    use std::net::{IpAddr, Ipv4Addr, SocketAddr};
```
warning: unused import: `Ipv4Addr`
   --> src/dist/http.rs:325:28
    |
325 |     use std::net::{IpAddr, Ipv4Addr, SocketAddr};
    |                            ^^^^^^^^
```

2020-11-17 12:26 UTC, gww-parity approved these changes
Now I see no warnings and nice rustfmt on files. Thank you!

In future it will be highly appreciated if I could see rustfmt/style in separate commit, so commits with actual logical changes are easier to focus on. 

Thank you!

2020-11-17 12:27 UTC, merged